-----------INSERT DATA INTO TABLE --------------------------
DROP PROCEDURE HM_BANK_INFO; 
DROP PROCEDURE HM_CAR_INFO; 
DROP PROCEDURE HM_EDUCATION_TABLE; 
DROP PROCEDURE HM_FAMILY_TABLE; 
DROP PROCEDURE HM_HOUSE_TYPE; 
DROP PROCEDURE HM_JOB_TABLE;
DROP PROCEDURE HM_JOB_TYPE_N_DATA_ENTRY;
DROP PROCEDURE HM_PERSON_ADDRESS;
DROP PROCEDURE HM_PERSON_DATA_ENTRY;
DROP PROCEDURE HM_PHONE_TABLE;
DROP PROCEDURE HM_PHYSICAL_DESCRIPTION; 

--INSERT VALUES INTO H_BODY_DECORATION_MARK_N TABLE
INSERT INTO  H_BODY_DECORATION_MARK_N (BODY_DECORATION_MARK_ID, MARK_DESCRIPTION)
VALUES(1,'TATTOO');
INSERT INTO  H_BODY_DECORATION_MARK_N (BODY_DECORATION_MARK_ID, MARK_DESCRIPTION)
VALUES(2,'PIERCING');
INSERT INTO  H_BODY_DECORATION_MARK_N (BODY_DECORATION_MARK_ID, MARK_DESCRIPTION)
VALUES(3,'BIRTH MARK');
/
--INSERT VALUES INTO H_EDUCATION_TABLE_N
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(1, 'BELOW_12_CLASS');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(2, 'COLLEGE');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(3, 'TECHNICAL COLLEGE');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(4, 'BACHELOR');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(5, 'MASTER');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(6, 'M-PHIL');
INSERT INTO H_EDUCATION_TABLE_N (EDUCATION_LEVEL_ID, E_LEVEL)
VALUES(7, 'DOCTORATE');

/
--insert values H_RELATION_TYPE_N
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (1, 'G_GRAND_FATHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (2, 'G_GRAND_MOTHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (3, 'GRAND_FATHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (4, 'GRAND_MOTHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (5, 'FATHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (6, 'MOTHER');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (7, 'HUSBAND');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (8, 'WIFE');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (9, 'SON');
INSERT INTO H_RELATION_TYPE_N(RELATION_TYPE_ID, RELATION_TYPE_CATEGORY)
VALUES (10, 'DAUGHTER');
/

/*--INSERT VALUES INTO H_CAR_OWNED_NORMALIZE
INSERT INTO H_CAR_OWNED_NORMALIZE(CAR_OWNED, YES_NO)
VALUES (0, 'NO');
INSERT INTO H_CAR_OWNED_NORMALIZE(CAR_OWNED, YES_NO)
VALUES (1, 'YES');
/
*/

--INSERT VALUES INTO H_HOUSE_TYPE_N
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (1, 'APPARTMENT');
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (2, 'BUNGALOW');
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (3, 'CONDOMINIUM');
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (4, 'COTTAGE');
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (5, 'VILLA');
INSERT INTO H_HOUSE_TYPE_N(house_type_ID, house_type_name)
VALUES (6, 'PALACE');
/
--- INSERT DATA INTO H_PHONE_NUMBER_N

INSERT INTO H_PHONE_NUMBER_N(TYPE_OF_PHONE_ID,TYPE_DESCRIPTION)
VALUES (1, 'MOBILE_PHONE');
INSERT INTO H_PHONE_NUMBER_N(TYPE_OF_PHONE_ID,TYPE_DESCRIPTION)
VALUES (2, 'HOME_PHONE');
INSERT INTO H_PHONE_NUMBER_N(TYPE_OF_PHONE_ID,TYPE_DESCRIPTION)
VALUES (3, 'OFFICE_PHONE');
INSERT INTO H_PHONE_NUMBER_N(TYPE_OF_PHONE_ID,TYPE_DESCRIPTION)
VALUES (4, 'GOOGLE_VOICE');
/
/*
----INSERT VALUE INTO H_PERSON_ADDRESS_N
INSERT INTO H_PERSON_ADDRESS_NORMALIZE(ACTIVE_INACTIVE,A_I_DESCRIPTION)
VALUES (0, 'NO');
INSERT INTO H_PERSON_ADDRESS_NORMALIZE(ACTIVE_INACTIVE,A_I_DESCRIPTION)
VALUES (1, 'YES');
/
*/
--------------------
--INSERT VALUES INTO H_JOB_TYPE_NORMALIZE
CREATE OR REPLACE PROCEDURE HM_JOB_TYPE_N_DATA_ENTRY(
JOB_DESC_CATEGORY IN H_JOB_TYPE_N.JOB_DESCRIPTION%TYPE )
IS
V_COUNT INTEGER;
V_JOB_TYPE_ID  H_JOB_TYPE_N.JOB_TYPE_ID%TYPE;
BEGIN
 SELECT COUNT(JOB_TYPE_ID) INTO V_COUNT FROM h_job_type_n;
        IF V_COUNT=0
            THEN V_JOB_TYPE_ID:=1;
        ELSE
            SELECT MAX(JOB_TYPE_ID)+1 INTO V_JOB_TYPE_ID FROM h_job_type_n; 
        END IF;
        INSERT INTO H_JOB_TYPE_N(JOB_TYPE_ID, JOB_DESCRIPTION)
        VALUES (V_JOB_TYPE_ID ,JOB_DESC_CATEGORY);
END HM_JOB_TYPE_N_DATA_ENTRY;
/

SET SERVEROUTPUT ON
DECLARE
var11 varchar2(30000):= 'ACCOUNTING,ADMIN_CLERICAL,AUTOMOTIVE,BANKING,BIOTECH,BROADCAST_JOURNALISM,BUSINESS,CONSTRUCTION,CONSULTANT,CUSTOMER_SERVICE,DESIGN,DISTRIBUTION_SHIPPING,EDUCATION_TEACHING,ENGINEERING,ENTRY_LEVEL,FINANCE,GENERAL_LABOR,GOVERNMENT,GROCERY,HEALTH_CARE,HOTEL_HOSPITALITY,HUMAN_RESOURCE,INFORMATION_TECHNOLOGY,INSURANCE,MANAGEMENT,MANUFACTURING,MARKETING,NURSE,RESEARCH,RESTAURANT,RETIREMENT,SALES,TELECOMMUNICATIONS,TRANSPORTATION,WAREHOUSE';

BEGIN  
    FOR I IN (SELECT trim(regexp_substr(var11, '[^,]+', 1, LEVEL)) M 
         from dual 
         CONNECT BY LEVEL <= regexp_count(var11, ',')+1
    )
    LOOP
    HM_JOB_TYPE_N_DATA_ENTRY(I.M);
    END LOOP;
END;
/
-----------------



-----------------PROCEDURE FOR main data enty-----------------

--PROCEDURE FOR  HM_PERSON_DATA_ENTRY
CREATE OR REPLACE PROCEDURE HM_PERSON_DATA_ENTRY(
P_LAST_NAME IN H_PERSON_NAME.LAST_NAME%TYPE,
P_FIRST_NAME IN H_PERSON_NAME.FIRST_NAME%TYPE,
P_DATE_OF_BIRTH IN h_person_name.date_of_birth%TYPE,
P_GENDER IN h_person_name.GENDER%TYPE,
P_SSN IN H_PERSON_NAME.SSN%TYPE,
P_EMAIL IN H_PERSON_NAME.E_MAIL%TYPE,
P_NATIONALITY IN H_PERSON_NAME.NATIONALITY%TYPE
)
IS
V_COUNT INTEGER;
V_PERSON_ID H_PERSON_NAME.PERSON_ID%TYPE;

BEGIN
 SELECT COUNT(PERSON_ID) INTO V_COUNT FROM H_PERSON_NAME;
        IF V_COUNT=0
            THEN V_PERSON_ID:=1;
        ELSE
            SELECT MAX(PERSON_ID)+1 INTO V_PERSON_ID FROM H_PERSON_NAME; 
        END IF;
        INSERT INTO H_PERSON_NAME(PERSON_ID,LAST_NAME, FIRST_NAME,date_of_birth,GENDER,SSN,E_MAIL,NATIONALITY)
        VALUES (V_PERSON_ID,P_LAST_NAME ,P_FIRST_NAME,P_DATE_OF_BIRTH,P_GENDER,P_SSN,P_EMAIL,P_NATIONALITY);
        
END HM_PERSON_DATA_ENTRY;
/

--PROCEDURE FOR   H_PERSON_ADDRESS
CREATE OR REPLACE PROCEDURE HM_PERSON_ADDRESS(
P_PERSON_ID IN h_person_address.PERSON_ID%TYPE,
P_ADD_LINE1 IN h_person_address.address_line_1%TYPE,
P_ADD_LINE2 IN h_person_address.address_line_2%TYPE,
P_CITY IN h_person_address.CITY%TYPE,
P_ZIP IN h_person_address.zip_code%TYPE,
P_STATE IN H_PERSON_ADDRESS.STATE%TYPE,
P_DATE_IN IN H_PERSON_ADDRESS.DATE_IN%TYPE,
P_DATE_OUT IN H_PERSON_ADDRESS.DATE_OUT%TYPE,
P_ACTIVE IN h_person_address.active%TYPE
)
IS
V_COUNT INTEGER;
V_ADDRESS_ID h_person_address.address_id%TYPE;

BEGIN
 SELECT COUNT(ADDRESS_ID) INTO V_COUNT FROM H_PERSON_ADDRESS;
        IF V_COUNT=0
            THEN V_ADDRESS_ID:=1;
        ELSE
            SELECT MAX(ADDRESS_ID)+1 INTO V_ADDRESS_ID FROM H_PERSON_ADDRESS; 
        END IF;
        INSERT INTO H_PERSON_ADDRESS(address_id, person_id,address_line_1,address_line_2,CITY,zip_code,STATE,DATE_IN,DATE_OUT,ACTIVE)
        VALUES (V_ADDRESS_ID ,P_PERSON_ID,P_ADD_LINE1,P_ADD_LINE2,P_CITY,P_ZIP,P_STATE,P_DATE_IN,P_DATE_OUT,P_ACTIVE);
END  HM_PERSON_ADDRESS;
/
--INSERT INTO H_PERSON_ADDRESS(address_id, person_id,address_line_1,address_line_2,CITY,zip_code,STATE,DATE_IN,DATE_OUT,ACTIVE)
--VALUES (1,2,'34 SASKE ST','apt 3','SUMMERVILE',67578,'MA','2-FEB-1955','2-JAN-1986','1');
--BEGIN
--HM_PERSON_ADDRESS(2,'34 SASKE ST','apt 3','SUMMERVILE',67578,'MA','2-FEB-1955','2-JAN-1986','1');
--END;



---PROCEDURE FOR H_HOUSE_TYPE
CREATE OR REPLACE PROCEDURE HM_HOUSE_TYPE(
P_ADDRESS_ID IN H_HOUSE_TYPE.ADDRESS_ID%TYPE,
P_HOUSE_TYPE IN  H_HOUSE_TYPE.HOUSE_TYPE_ID%TYPE
)
IS
V_COUNT INTEGER;
V_HOUSE_ID H_HOUSE_TYPE.HOUSE_ID%TYPE;

BEGIN
 SELECT COUNT(HOUSE_ID) INTO V_COUNT FROM H_HOUSE_TYPE;
        IF V_COUNT=0
            THEN V_HOUSE_ID:=1;
        ELSE
            SELECT MAX(HOUSE_ID)+1 INTO V_HOUSE_ID FROM H_HOUSE_TYPE; 
        END IF;
        INSERT INTO H_HOUSE_TYPE(HOUSE_id, ADDRESS_id, HOUSE_TYPE_ID)
        VALUES (V_HOUSE_ID ,P_ADDRESS_ID,P_HOUSE_TYPE);
END  HM_HOUSE_TYPE;
/


---PROCEDURE FOR H_PHYSICAL_DESCRIPTION
CREATE OR REPLACE PROCEDURE HM_PHYSICAL_DESCRIPTION(
P_PERSON_ID IN H_PHYSICAL_DESCRIPTION.PERSON_ID%TYPE,
P_EYE_COLOR IN H_PHYSICAL_DESCRIPTION.EYE_COLOR%TYPE,
P_HAIR_COLOR IN H_PHYSICAL_DESCRIPTION.HAIR_COLOR%TYPE,
P_HEIGHT IN H_PHYSICAL_DESCRIPTION.HEIGHT%TYPE,
P_WEIGHT IN H_PHYSICAL_DESCRIPTION.WEIGHT%TYPE,
P_BODY_DECORATION IN H_PHYSICAL_DESCRIPTION.BODY_DECORATION_MARK_ID%TYPE,
P_BODY_DECR_MARK IN H_PHYSICAL_DESCRIPTION.BODY_DECORATION_MARK_POSITION%TYPE,
P_OTHER IN H_PHYSICAL_DESCRIPTION.OTHER_DESCRIPTION%TYPE
)
IS
V_COUNT INTEGER;
V_PHY_ID  H_PHYSICAL_DESCRIPTION.PHYSICAL_DESCRIPTION_ID%TYPE;

BEGIN
 SELECT COUNT(PHYSICAL_DESCRIPTION_ID) INTO V_COUNT FROM h_physical_dEscription;
        IF V_COUNT=0
            THEN V_PHY_ID:=1;
        ELSE
            SELECT MAX(PHYSICAL_DESCRIPTION_ID)+1 INTO V_PHY_ID FROM  h_physical_dEscription; 
        END IF;
        INSERT INTO H_PHYSICAL_DESCRIPTION(PHYSICAL_DESCRIPTION_id, PERSON_ID, EYE_COLOR,HAIR_COLOR,HEIGHT,WEIGHT,BODY_DECORATION_MARK_ID,BODY_DECORATION_MARK_POSITION,OTHER_DESCRIPTION)
        VALUES (V_PHY_ID ,P_PERSON_ID,P_EYE_COLOR,P_HAIR_COLOR,P_HEIGHT,P_WEIGHT,P_BODY_DECORATION,P_BODY_DECR_MARK,P_OTHER);
END  HM_PHYSICAL_DESCRIPTION;
/


---PROCEDURE FOR H_CAR_INFO
CREATE OR REPLACE PROCEDURE HM_CAR_INFO(
P_PERSON_ID IN H_CAR_INFO.PERSON_ID%TYPE,
P_CAR_OWNED IN H_CAR_INFO.CAR_OWNED%TYPE,
P_DRIVING_LICENSE IN H_CAR_INFO.DRIVING_LICENSE%TYPE,
P_CARPLATE IN H_CAR_INFO.CARPLATE_NUMBER%TYPE
)
IS
V_COUNT INTEGER;
V_CAR_ID H_CAR_INFO.CAR_ID%TYPE;

BEGIN
 SELECT COUNT(CAR_ID) INTO V_COUNT FROM H_CAR_INFO;
        IF V_COUNT=0
            THEN V_CAR_ID:=1;
        ELSE
            SELECT MAX(CAR_ID)+1 INTO V_CAR_ID FROM H_CAR_INFO;
        END IF;
        INSERT INTO H_CAR_INFO(CAR_ID, PERSON_id, CAR_OWNED,DRIVING_LICENSE,CARPLATE_NUMBER)
        VALUES (V_CAR_ID ,P_PERSON_ID,P_CAR_OWNED,P_DRIVING_LICENSE,P_CARPLATE);
END  HM_CAR_INFO;
/


---PROCEDURE FOR H_BANK_INFO
CREATE OR REPLACE PROCEDURE HM_BANK_INFO(
P_PERSON_ID IN H_BANK_INFO.PERSON_ID%TYPE,
P_REG_NO IN H_BANK_INFO.REG_NO%TYPE,
P_ACCOUNT_NO IN H_BANK_INFO.ACCOUNT_NO%TYPE,
P_BANK_NAME IN H_BANK_INFO.BANK_NAME%TYPE
)
IS
V_COUNT INTEGER;
V_BANK_ID H_BANK_INFO.BANK_ID%TYPE;

BEGIN
 SELECT COUNT(BANK_ID) INTO V_COUNT FROM H_BANK_INFO;
        IF V_COUNT=0
            THEN V_BANK_ID:=1;
        ELSE
            SELECT MAX(BANK_ID)+1 INTO V_BANK_ID FROM H_BANK_INFO;
        END IF;
        INSERT INTO H_BANK_INFO(BANK_ID, PERSON_ID, REG_NO,ACCOUNT_NO,BANK_NAME)
        VALUES (V_BANK_ID ,P_PERSON_ID,P_REG_NO,P_ACCOUNT_NO,P_BANK_NAME);
END  HM_BANK_INFO;
/


---PROCEDURE FOR FAMILY TABLE
CREATE OR REPLACE PROCEDURE HM_FAMILY_TABLE(
P_PERSON_ID IN H_FAMILY_TABLE.PERSON_ID%TYPE,
P_RELA_PER_ID IN H_FAMILY_TABLE.RELATIVE_PERSON_ID%TYPE,
P_RELATION_TYPE IN H_FAMILY_TABLE.RELATION_TYPE_ID%TYPE
)
IS
V_COUNT INTEGER;
V_FAMILY_ID H_FAMILY_TABLE.FAMILY_TABLE_ID%TYPE;

BEGIN
 SELECT COUNT(FAMILY_TABLE_ID) INTO V_COUNT FROM H_FAMILY_TABLE;
        IF V_COUNT=0
            THEN V_FAMILY_ID:=1;
        ELSE
            SELECT MAX(FAMILY_TABLE_ID)+1 INTO V_FAMILY_ID FROM H_FAMILY_TABLE;
        END IF;
        INSERT INTO H_FAMILY_TABLE(FAMILY_TABLE_ID, PERSON_ID,RELATIVE_PERSON_ID,RELATION_TYPE_ID)
        VALUES (V_FAMILY_ID ,P_PERSON_ID,P_RELA_PER_ID,P_RELATION_TYPE);
END  HM_FAMILY_TABLE;
/


 ---PROCEDURE FOR EDUCATION TABLE
CREATE OR REPLACE PROCEDURE HM_EDUCATION_TABLE(
P_PERSON_ID IN H_EDUCATION_TABLE.PERSON_ID%TYPE,
P_EDU_LEV IN H_EDUCATION_TABLE.EDUCATION_LEVEL_ID%TYPE,
P_YEAR_COMPLE IN H_EDUCATION_TABLE.YEAR_OF_COMPLETE%TYPE
)
IS
V_COUNT INTEGER;
V_EDU_ID H_EDUCATION_TABLE.EDUCATION_ID%TYPE;

BEGIN
 SELECT COUNT(EDUCATION_ID) INTO V_COUNT FROM H_EDUCATION_TABLE;
        IF V_COUNT=0
            THEN V_EDU_ID:=1;
        ELSE
            SELECT MAX(EDUCATION_ID)+1 INTO V_EDU_ID FROM H_EDUCATION_TABLE;
        END IF;
        INSERT INTO H_EDUCATION_TABLE(EDUCATION_ID, PERSON_ID,EDUCATION_LEVEL_ID,YEAR_OF_COMPLETE)
        VALUES (V_EDU_ID ,P_PERSON_ID,P_EDU_LEV,P_YEAR_COMPLE);
END  HM_EDUCATION_TABLE;
/


 ---PROCEDURE FOR  JOB TABLE
CREATE OR REPLACE PROCEDURE HM_JOB_TABLE(
P_PERSON_ID IN H_JOB_TABLE.PERSON_ID%TYPE,
P_JOB IN H_JOB_TABLE.JOB_TYPE_ID%TYPE
)
IS
V_COUNT INTEGER;
V_JOB_ID H_JOB_TABLE.JOB_TABLE_ID%TYPE;

BEGIN
 SELECT COUNT(JOB_TABLE_ID) INTO V_COUNT FROM H_JOB_TABLE;
        IF V_COUNT=0
            THEN V_JOB_ID:=1;
        ELSE
            SELECT MAX(JOB_TABLE_ID)+1 INTO V_JOB_ID FROM H_JOB_TABLE;
        END IF;
        INSERT INTO H_JOB_TABLE(JOB_TABLE_ID, PERSON_ID, JOB_TYPE_ID)
        VALUES (V_JOB_ID ,P_PERSON_ID,P_JOB);
END  HM_JOB_TABLE;
/


---PROCEDURE FOR  PHONE NUMBER 
CREATE OR REPLACE PROCEDURE HM_PHONE_TABLE(
P_PERSON_ID IN H_PHONE_NUMBER.PERSON_ID%TYPE,
P_PHONE IN H_PHONE_NUMBER.PHONE_NUMBER%TYPE,
P_TYPE IN H_PHONE_NUMBER.TYPE_OF_PHONE_ID%TYPE
)
IS

BEGIN
        INSERT INTO H_PHONE_NUMBER(PERSON_ID,PHONE_NUMBER,TYPE_OF_PHONE_ID)
        VALUES (P_PERSON_ID, P_PHONE, P_TYPE);
END  HM_PHONE_TABLE;
/

-------------------DATA ENTRY----------------
------------------- PERSON DATA :1
BEGIN
HM_PERSON_DATA_ENTRY('HANKS','TOM','10-NOV-1960','M',256235878,'tom_hanks@gamil.com','USA');

HM_PERSON_ADDRESS(1,'2 hill view st','apt 2','cambridge',21254,'MA','12-JAN-1980','','1');


HM_HOUSE_TYPE(1,1);

HM_PHYSICAL_DESCRIPTION(1,'BROWN','BLACK',178,73,1,'SHOULDER','NULL');

HM_CAR_INFO(1,1,'SB7890654','8D7546');

HM_BANK_INFO(1,4781,5678908475,'SANTANDER');

HM_FAMILY_TABLE(1,2,5);

HM_EDUCATION_TABLE(1,3,'12-MAY-1980');

HM_JOB_TABLE(1,2);

HM_PHONE_TABLE(1,6172349876,1);
END;
/
------------------- PERSON DATA : 2
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,SSN,'EMAIL','NATIONALITY');
HM_PERSON_DATA_ENTRY('NIRO','ROBART DE','11-OCT-1945','M',233653456,'DE_NERO@gamil.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP,'STATE',DATE_IN,DATE_OUT,'ACTIVE');

HM_PERSON_ADDRESS(2,'34 SASKE ST','apt 3','SUMMERVILE',67578,'MA','2-FEB-1955','','1');


--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(2,2);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(2,'BROWN','WHITE',172,65,3,'RIGHT LEG','NULL');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE','CAR PLATE NUMBER');
HM_CAR_INFO(2,0,'GY8793459','NULL');

--BANK_INFO(PERSON ID,REGNO,ACCOUNT NO,'BANK NAME');
HM_BANK_INFO(2,9870,3242536765,'BOA');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(2,1,9);

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,YEAR_COMPLETED);
HM_EDUCATION_TABLE(2,1,'12-JUN-1959');

--HM_JOB_TABLE(PERSONID,2);
HM_JOB_TABLE(1,18);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER,PHONE TYPE);
HM_PHONE_TABLE(2,6125467894,1);
END;
/
------------------- PERSON DATA: 3
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('WATSON','EMMA','25-FEB-1990','F',987342445,'e.watson@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP,'STATE','MOVE_IN','MOVE_OUT','ACTIVE');
HM_PERSON_ADDRESS(3,'2 hill view road','apt 2','CAMBRIDGE',21254,'MA','19-JULY-2011','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(3,2);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(3,'RED','BLACK',145,52,1,'LEFT FEET','NULL');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE','CAR PLATE NUMBER');
HM_CAR_INFO(3,0,'LB65768323','NULL');

--BANK_INFO(PERSON ID,REGNO,ACCOUNT NO,'BANK NAME');
HM_BANK_INFO(3,2547,2547879658,'NORDIA');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(3,1,8);

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL, COMPLETE_YEAR);
HM_EDUCATION_TABLE(3,3,'12-MAY-2009');

--HM_JOB_TABLE(PERSONID,2);
HM_JOB_TABLE(3,23);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER,PHONE TYPE);
HM_PHONE_TABLE(3,6236788954,1);
END;
/
------------------- PERSON DATA :4
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('LAWRENCE','JENNIFER','19-JAN-1992','F',254252478,'jene.lawrence@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(4,'34 SASKE LANE','apt 3','SUMMERVILE',67578,'MA','20-MAR-2012','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(4,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(4,'BLACK','BLONDE',150,47,1,'LEFT ARM','NULL');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE','CAR PLATE NUMBER');
HM_CAR_INFO(4,1,'BI2348869','8J8K93');

--BANK_INFO(PERSON ID,REGNO,ACCOUNT NO,'BANK NAME');
HM_BANK_INFO(4,5876,548759658,'CAPITAL ONE');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(4,2,8);

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(4,2,'16-MAY-2014');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(4,20);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER,PHONE TYPE);
HM_PHONE_TABLE(4,6173456789,1);
END;
/

------------------- PERSON DATA :5
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('UPTON','KATE','19-JAN-1988','F',45695879,'k.upton@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(5,'79 ROSE ST','apt 121','BOSTON',45367,'MA','20-MAR-2008','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(5,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(5,'BLACK','BLONDE',151,48,'','','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE','CAR PLATE NUMBER');
HM_CAR_INFO(5,1,'BI2387956','8J8Y93');

--BANK_INFO(PERSON ID,REGNO,ACCOUNT NO,'BANK NAME');
HM_BANK_INFO(5,5896,54875785,'CAPITAL ONE');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(5,1,10);

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(5,4,'1-MAY-2010');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(5,20);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER,PHONE TYPE);
HM_PHONE_TABLE(5,6185746145,1);
END;
/

------------------- PERSON DATA :6
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('MURPHY','EDDIE','19-JAN-1986','M',456980765,'em@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(6,'7 CLEAN ST','apt 22','BOSTON',45357,'MA','20-MAR-2005','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(6,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(6,'BLACK','BROWN',165,75,'1','LEFT ARM','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE 8D','CAR PLATE NUMBER 6 DIGIT');
HM_CAR_INFO(6,1,'BI238756','8J8IE0');

--BANK_INFO(PERSON ID,REGNO 4D ,ACCOUNT NO  10D,'BANK NAME');
HM_BANK_INFO(6,5786,5487896475,'CAPITAL ONE');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(6,1,9);

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(6,4,'1-AUG-2008');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(6,13);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER 10D ,PHONE TYPE);
HM_PHONE_TABLE(6,6185745486,1);
END;
/
------------------- PERSON DATA :7
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN 10D,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('FREEMAN','MORGAN','1-JUN-1937','M',4545185796,'free.morgan@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP 5D,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(7,'7 holywood ST','apt 12','BOSTON',45784,'MA','2-APR-2005','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(7,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(7,'BLACK','BROWN',175,76,'','','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE 8D','CAR PLATE NUMBER 6 DIGIT');
HM_CAR_INFO(7,1,'BI238566','8LMIE0');

--BANK_INFO(PERSON ID,REGNO 4D ,ACCOUNT NO  10D,'BANK NAME');
HM_BANK_INFO(7,8526,5487845856,'PEOPLES BANK');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(7,'8','8');

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(7,4,'1-SEP-1950');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(7,2);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER 10D ,PHONE TYPE);
HM_PHONE_TABLE(7,6185182548,1);
END;
/
------------------- PERSON DATA : 8
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN 10D,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('KIDMAN','NICOLE','1-JUN-1967','F',1426578459,'N.KIDMAN@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP 5D,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(8,'7 holywood ST','apt 12','BOSTON',45784,'MA','2-APR-2005','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(8,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(8,'BLUE','BLONDE',165,56,'','','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE 8D','CAR PLATE NUMBER 6 DIGIT');
HM_CAR_INFO(8,1,'BI278459','8LJI51');

--BANK_INFO(PERSON ID,REGNO 4D ,ACCOUNT NO  10D,'BANK NAME');
HM_BANK_INFO(8,7845,5847525874,'PEOPLES BANK');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(8,'7','7');

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(8,3,'1-SEP-1989');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(8,32);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER 10D ,PHONE TYPE);
HM_PHONE_TABLE(8,6151248795,1);
END;
/

------------------- PERSON DATA : 9
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN 10D,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('HEPBURN','AUDREY','4-MAY-1987','F',8475624589,'A.HEPBURN@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP 5D,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(9,'9 holywood GADE','apt 18','BOSTON',45784,'MA','2-APR-2009','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(9,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(9,'BROWN','BLACK',164,49,'','','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE 8D','CAR PLATE NUMBER 6 DIGIT');
HM_CAR_INFO(9,0,'BX215489','');

--BANK_INFO(PERSON ID,REGNO 4D ,ACCOUNT NO  10D,'BANK NAME');
HM_BANK_INFO(9,5645,5784584598,'PP BANK');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(9,'7','10');

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(9,4,'1-SEP-2007');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(9,4);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER 10D ,PHONE TYPE);
HM_PHONE_TABLE(9,6153625149,1);
END;
/

------------------- PERSON DATA : 10
BEGIN
--PERSON_DATA_ENTRY('LASTNAME','FIRSTNAME','DOB',GENDER,,SSN 10D,'EMAIL','COUNTRY');
HM_PERSON_DATA_ENTRY('DAMON','MATT','5-JAN-1970','M',8474598125,'M.DAMON@hotmail.com','USA');

--PERSON_ADDRESS(PERSONNO,'ADDRESS','ADDRESS2','CITY',ZIP 5D,'STATE','ADDRES_IN,'ADDRESS_OUT','ACTIVE=1');
HM_PERSON_ADDRESS(10,'31A SHARK GADE','apt 44','BOSTON',45784,'MA','23-APR-2017','','1');

--HOUSE_TYPE(ADDRESSID,HOUSETYPE);
HM_HOUSE_TYPE(10,1);

--PHYSICAL_DESCRIPTION(PERSONID,'EYECOLOR','HAIRCOLOR',HEIGHT,WEIGHT,BODYDECORATION MARK,'MARK POSITION','OTHER');
HM_PHYSICAL_DESCRIPTION(10,'BLUE','BLACK',169,69,'','','');

--CAR_INFO(PERSONID,CAROWNED,'DRIVING LICENSE 8D','CAR PLATE NUMBER 6 DIGIT');
HM_CAR_INFO(10,1,'LK542847','LOK542');

--BANK_INFO(PERSON ID,REGNO 4D ,ACCOUNT NO  10D,'BANK NAME');
HM_BANK_INFO(10,5845,5845784968,'PP BANK');

--FAMILY_TABLE(PERSON ID,RELATIVE PERSON ID,REALTIONSHIP);
HM_FAMILY_TABLE(10,'7','9');

--HM_EDUCATION_TABLE(PERSON ID ,EDUCATION LAVEL,'COMPLETE_YEAR');
HM_EDUCATION_TABLE(10,4,'1-SEP-1994');

--HM_JOB_TABLE(PERSONID,JOB_TYPE);
HM_JOB_TABLE(10,5);

--HM_PHONE_TABLE(PERSON ID ,PHONENUMBER 10D ,PHONE TYPE);
HM_PHONE_TABLE(10,6153624859,1);
END;
/



