DROP TABLE H_BANK_INFO CASCADE CONSTRAINTS;
drop table H_BODY_DECORATION_MARK_N CASCADE CONSTRAINTS;
drop table H_CAR_INFO CASCADE CONSTRAINTS;
drop table H_EDUCATION_TABLE CASCADE CONSTRAINTS;
drop table H_EDUCATION_TABLE_N CASCADE CONSTRAINTS;
drop table H_FAMILY_TABLE CASCADE CONSTRAINTS;
drop table H_HOUSE_TYPE CASCADE CONSTRAINTS;
drop table H_HOUSE_TYPE_N CASCADE CONSTRAINTS;
drop table H_JOB_TABLE CASCADE CONSTRAINTS;
drop table H_JOB_TYPE_N CASCADE CONSTRAINTS;
drop table H_PERSON_ADDRESS CASCADE CONSTRAINTS;
drop table H_PERSON_NAME CASCADE CONSTRAINTS;
drop table H_PHONE_NUMBER CASCADE CONSTRAINTS;
drop table H_PHONE_NUMBER_N CASCADE CONSTRAINTS;
drop table H_PHYSICAL_DESCRIPTION CASCADE CONSTRAINTS;
drop table H_RELATION_TYPE_N CASCADE CONSTRAINTS;


CREATE TABLE "H_PERSON_NAME"
(
"PERSON_ID" NUMBER(6,0),
"LAST_NAME" VARCHAR2(20) NOT NULL,
"FIRST_NAME" VARCHAR2(25) NOT NULL,
"DATE_OF_BIRTH" DATE,
"GENDER" VARCHAR2(1),
"SSN" NUMBER(11,0) UNIQUE,
"E_MAIL" VARCHAR2(25) UNIQUE,
"NATIONALITY" VARCHAR2 (15),

CONSTRAINT "PERSON_ID_PK" PRIMARY KEY ("PERSON_ID")
USING INDEX ENABLE
);
/

CREATE TABLE "H_PERSON_ADDRESS"
(
"ADDRESS_ID" NUMBER(6,0),
"PERSON_ID" NUMBER(6,0),
"ADDRESS_LINE_1" VARCHAR2(50),
"ADDRESS_LINE_2" VARCHAR2(50),
"CITY" VARCHAR2(30),
"ZIP_CODE" NUMBER(6,0),
"STATE" VARCHAR2(20),
"DATE_IN" DATE,
"DATE_OUT" DATE,
"ACTIVE" NUMBER(1,0),
CONSTRAINT "ADDRESS_ID_PK" PRIMARY KEY ("ADDRESS_ID")

USING INDEX ENABLE,
CONSTRAINT "H_PERSON_ADDRESS_ACTIVE_CHECK" CHECK ( "ACTIVE" IN(0,1)) ENABLE
);
/

CREATE TABLE "H_PHONE_NUMBER"
(
"PERSON_ID" NUMBER (6,0),
"PHONE_NUMBER" NUMBER(10,0),
"TYPE_OF_PHONE_ID" NUMBER(2,0),
CONSTRAINT "PERSON_ID_PHO_PK" PRIMARY KEY ("PERSON_ID")
USING INDEX ENABLE
);
/
CREATE TABLE "H_PHONE_NUMBER_N"
(
"TYPE_OF_PHONE_ID" NUMBER(2,0),
"TYPE_DESCRIPTION" VARCHAR2(25),
CONSTRAINT "TYPE_OF_PHONE_PK" PRIMARY KEY ("TYPE_OF_PHONE_ID")
USING INDEX ENABLE
);
/


CREATE TABLE "H_HOUSE_TYPE"
(
"HOUSE_ID" NUMBER(6,0),
"ADDRESS_ID" NUMBER(6,0),
"HOUSE_TYPE_ID" NUMBER(2,0),
CONSTRAINT "HOUSE_ID_PK" PRIMARY KEY ("HOUSE_ID")
USING INDEX ENABLE
);
/


CREATE TABLE "H_HOUSE_TYPE_N"
(
"HOUSE_TYPE_ID" NUMBER(2,0),
"HOUSE_TYPE_NAME" VARCHAR2(15),
CONSTRAINT "HOUSE_TYPE_PK" PRIMARY KEY ("HOUSE_TYPE_ID")
USING INDEX ENABLE
);
/

CREATE TABLE "H_PHYSICAL_DESCRIPTION"
(
"PHYSICAL_DESCRIPTION_ID" NUMBER(6,0),
"PERSON_ID" NUMBER(6,0),
"EYE_COLOR" VARCHAR2(10),
"HAIR_COLOR" VARCHAR2(10),
"HEIGHT" NUMBER(3,0),
"WEIGHT" NUMBER(3,0),
"BODY_DECORATION_MARK_ID" NUMBER(2,0),
"BODY_DECORATION_MARK_POSITION" VARCHAR2(20),
"OTHER_DESCRIPTION" VARCHAR2(35),
CONSTRAINT "PHYSICAL_DESCRIPTION_ID_PK" PRIMARY KEY ("PHYSICAL_DESCRIPTION_ID")

USING INDEX ENABLE
);
/
CREATE TABLE "H_BODY_DECORATION_MARK_N"
(
"BODY_DECORATION_MARK_ID" NUMBER(2,0),
"MARK_DESCRIPTION" VARCHAR2(15),
CONSTRAINT "BODY_DECORATION_MARK_PK" PRIMARY KEY ("BODY_DECORATION_MARK_ID")
USING INDEX ENABLE
);
/

CREATE TABLE "H_CAR_INFO"
(
"CAR_ID" NUMBER(8,0),
"PERSON_ID" NUMBER(6,0),
"CAR_OWNED" NUMBER(1,0),
"DRIVING_LICENSE" VARCHAR2(10),
"CARPLATE_NUMBER" VARCHAR2(6),

CONSTRAINT "CAR_ID_PK" PRIMARY KEY ("CAR_ID")
USING INDEX ENABLE,
CONSTRAINT "H_CAR_INFO_CAR_OWNED_CHECK" CHECK ( "CAR_OWNED" IN(0,1)) ENABLE
);
/

CREATE TABLE "H_BANK_INFO"
(
"BANK_ID" NUMBER(8,0),
"PERSON_ID" NUMBER(6,0),
"REG_NO" NUMBER(4,0),
"ACCOUNT_NO" NUMBER(10,0),
"BANK_NAME" VARCHAR2(25),

CONSTRAINT "BANK_ID_PK" PRIMARY KEY ("BANK_ID")

USING INDEX ENABLE
);
/

CREATE TABLE "H_FAMILY_TABLE"
(
"FAMILY_TABLE_ID" NUMBER(6,0),
"PERSON_ID" NUMBER(6,0),
"RELATIVE_PERSON_ID" NUMBER(6,0),
"RELATION_TYPE_ID" NUMBER(2,0),

CONSTRAINT "FAMILY_TABLE_ID_PK" PRIMARY KEY ("FAMILY_TABLE_ID")

USING INDEX ENABLE
);
/

CREATE TABLE "H_RELATION_TYPE_N"
(
"RELATION_TYPE_ID" NUMBER(2,0),
"RELATION_TYPE_CATEGORY" VARCHAR2(15),
CONSTRAINT "RELATION_TYPE_PK" PRIMARY KEY ("RELATION_TYPE_ID")
USING INDEX ENABLE
);
/

CREATE TABLE "H_EDUCATION_TABLE"
(
"EDUCATION_ID" NUMBER(6,0),
"PERSON_ID" NUMBER(6,0),
"EDUCATION_LEVEL_ID" NUMBER(2,0),
"YEAR_OF_COMPLETE" DATE,

CONSTRAINT "EDUCATION_ID_PK" PRIMARY KEY ("EDUCATION_ID")
USING INDEX ENABLE
);
/


CREATE TABLE "H_EDUCATION_TABLE_N"
(
"EDUCATION_LEVEL_ID" NUMBER(2,0),
"E_LEVEL" VARCHAR2(25),
CONSTRAINT "EDUCATION_LEVEL_PK" PRIMARY KEY ("EDUCATION_LEVEL_ID")
USING INDEX ENABLE
);
/

CREATE TABLE "H_JOB_TABLE"
(
"JOB_TABLE_ID" NUMBER(6,0),
"PERSON_ID" NUMBER(6,0),
"JOB_TYPE_ID" NUMBER(2,0),

CONSTRAINT "JOB_TABLE_ID_PK" PRIMARY KEY ("JOB_TABLE_ID")

USING INDEX ENABLE
);
/

CREATE TABLE "H_JOB_TYPE_N"
(
"JOB_TYPE_ID" NUMBER(2,0),
"JOB_DESCRIPTION" VARCHAR2(30),
CONSTRAINT "JOB_TYPE_PK" PRIMARY KEY ("JOB_TYPE_ID")
USING INDEX ENABLE
);
/

--- ADDING FOREIGN KEY
ALTER TABLE  "H_PERSON_ADDRESS" ADD CONSTRAINT "H_PERSON_ADDRESS_PERSON_ID_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;

/
ALTER TABLE  "H_PHONE_NUMBER" ADD CONSTRAINT "H_PHONE_NUMBER_PERSON_ID_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/
ALTER TABLE  "H_PHONE_NUMBER" ADD CONSTRAINT "H_PHONE_NUMBER_TYPE_OF_PHONE_CON" FOREIGN KEY ("TYPE_OF_PHONE_ID")  
REFERENCES  "H_PHONE_NUMBER_N" ("TYPE_OF_PHONE_ID")  ENABLE;
/

ALTER TABLE  "H_HOUSE_TYPE" ADD CONSTRAINT "H_HOUSE_TYPE_ADDRESS_ID_CON" FOREIGN KEY ("ADDRESS_ID")  
REFERENCES  "H_PERSON_ADDRESS" ("ADDRESS_ID")  ENABLE;
/

ALTER TABLE  "H_HOUSE_TYPE" ADD CONSTRAINT "H_HOUSE_TYPE_HOUSE_TYPE_CON" FOREIGN KEY ("HOUSE_TYPE_ID")  
REFERENCES  "H_HOUSE_TYPE_N" ("HOUSE_TYPE_ID")  ENABLE;
/

ALTER TABLE  "H_PHYSICAL_DESCRIPTION" ADD CONSTRAINT "H_PHYSICAL_DESCRIPTION_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_PHYSICAL_DESCRIPTION" ADD CONSTRAINT "H_PHYSICAL_DESCRIPTION_BODY_DECORATION_MARK_FK_CON" FOREIGN KEY ("BODY_DECORATION_MARK_ID")  
REFERENCES  "H_BODY_DECORATION_MARK_N" ("BODY_DECORATION_MARK_ID")  ENABLE;
/

ALTER TABLE  "H_CAR_INFO" ADD CONSTRAINT "H_CAR_INFO_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_BANK_INFO" ADD CONSTRAINT "H_BANK_INFO_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_FAMILY_TABLE" ADD CONSTRAINT "H_FAMILY_TABLE_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_FAMILY_TABLE" ADD CONSTRAINT "H_FAMILY_TABLE_RELATION_TYPE_FK_CON" FOREIGN KEY ("RELATION_TYPE_ID")  
REFERENCES  "H_RELATION_TYPE_N" ("RELATION_TYPE_ID")  ENABLE;
/

ALTER TABLE  "H_EDUCATION_TABLE" ADD CONSTRAINT "H_EDUCATION_TABLE_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_EDUCATION_TABLE" ADD CONSTRAINT "H_EDUCATION_TABLE_EDUCATION_LEVEL_FK_CON" FOREIGN KEY ("EDUCATION_LEVEL_ID")  
REFERENCES  "H_EDUCATION_TABLE_N" ("EDUCATION_LEVEL_ID")  ENABLE;
/

ALTER TABLE  "H_JOB_TABLE" ADD CONSTRAINT "H_JOB_TABLE_PERSON_ID_FK_CON" FOREIGN KEY ("PERSON_ID")  
REFERENCES  "H_PERSON_NAME" ("PERSON_ID")  ENABLE;
/

ALTER TABLE  "H_JOB_TABLE" ADD CONSTRAINT "H_JOB_TABLE_JOB_TYPE_FK_CON" FOREIGN KEY ("JOB_TYPE_ID")  
REFERENCES  "H_JOB_TYPE_N" ("JOB_TYPE_ID")  ENABLE;
/








